version: '3.9'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-test}
    ports:
      - '${DB_PORT:-27017}:27017'
    volumes:
      - six-cities_data:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: six-cities_mongo_express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-test}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER:-admin}:${DB_PASSWORD:-test}@db:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD:-test}

volumes:
  six-cities_data:
