version: '3.9'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-test}
    ports:
      - '${DB_PORT:-27017}:27017'
    volumes:
      - six-cities_data:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: six-cities_mongo_express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-test}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER:-admin}:${DB_PASSWORD:-test}@db:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD:-test}

  redis:
    image: redis:7-alpine
    container_name: six-cities_redis
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    # Only pass --requirepass if REDIS_PASSWORD is set
    command: >
      sh -c 'if [ -n "$$REDIS_PASSWORD" ]; then
               exec redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD";
             else
               exec redis-server --appendonly yes;
             fi'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    volumes:
      - six-cities_redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '$$REDIS_PASSWORD', 'PING']
      interval: 10s
      timeout: 3s
      retries: 5

  redis_ui:
    image: rediscommander/redis-commander:latest
    container_name: six-cities_redis_ui
    restart: always
    ports:
      - '8082:8081'
    environment:
      # name:host:port:db:password
      REDIS_HOSTS: 'local:redis:6379:${REDIS_DB:-0}:${REDIS_PASSWORD:-}'
      HTTP_USER: ${HTTP_USER:-admin}
      HTTP_PASSWORD: ${HTTP_PASSWORD:-test}
    depends_on:
      redis:
        condition: service_healthy

volumes:
  six-cities_data:
  six-cities_redis_data:
