openapi: 3.1.0
info:
  title: API server for «Six cities» project.
  description: |-
    * The list of resources and routes for «Six cities».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: rent-offers
    description: Actions with rent offers.
  - name: cities
    description: Actions with cities.
  - name: comments
    description: Actions with rent comments.
  - name: users
    description: Actions with rent users.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: User sign up
      description: Sign up a new user.

      requestBody:
        description: The data to create a new user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true

      responses:
        "201":
          description: User is signed up. User's object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

        "409":
          description: The user with such an email already exists.

  /users/login:
    post:
      tags:
        - users
      summary: User sign in
      description: User sign in based on login and password

    get:
      tags:
        - users
      summary: Check of user's status
      description: Returns authorized user data

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Upload avatar image
      description: Uploads an image of user's avatar. The image should be in `png` or `jpg` format.

components:
  schemas:
    createUser:
      type: object

      properties:
        email:
          type: string
          example: john.lennon@gmail.com

        firstName:
          type: string
          example: John

        lastName:
          type: string
          example: Lennon

        password:
          type: string
          example: 123456

    user:
      type: object

      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        email:
          type: string
          example: john.lennon@gmail.com
